// Generated by delombok at Tue Jan 02 01:24:37 CET 2024
/*
 * Copyright (C) 2017-2023 Dominic Heutelbeck (dominic@heutelbeck.com)
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.sapl.prp.index.canonical;

import java.util.Objects;

public class Literal {
    private final Bool    bool;
    private final boolean negated;
    private int           hash;
    private boolean       hasHashCode;

    public Literal(final Bool bool) {
        this(bool, false);
        java.util.Objects.requireNonNull(bool, "bool is marked non-null but is null");
    }

    public boolean isImmutable() {
        return bool.isImmutable();
    }

    public boolean evaluate() {
        return negated ^ bool.evaluate();
    }

    public Literal negate() {
        return new Literal(bool, !negated);
    }

    public boolean sharesBool(final Literal other) {
        return bool.equals(other.bool);
    }

    public boolean sharesNegation(final Literal other) {
        return negated == other.negated;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Literal other = (Literal) obj;
        if (negated != other.negated) {
            return false;
        }
        if (hashCode() != obj.hashCode()) {
            return false;
        }
        return bool.equals(other.bool);
    }

    @Override
    public int hashCode() {
        if (!hasHashCode) {
            hash        = Objects.hash(bool, negated);
            hasHashCode = true;
        }
        return hash;
    }

    @java.lang.SuppressWarnings("all")
    // @lombok.Generated
    public Literal(final Bool bool, final boolean negated) {
        java.util.Objects.requireNonNull(bool, "bool is marked non-null but is null");
        this.bool    = bool;
        this.negated = negated;
    }

    @java.lang.SuppressWarnings("all")
    // @lombok.Generated
    public Bool getBool() {
        return this.bool;
    }

    @java.lang.SuppressWarnings("all")
    // @lombok.Generated
    public boolean isNegated() {
        return this.negated;
    }
}
